# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import database_service_pb2 as database__service__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in database_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DatabaseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserCallsignChanges = channel.unary_unary(
                '/DatabaseService/GetUserCallsignChanges',
                request_serializer=database__service__pb2.UserCallsignChangesRequest.SerializeToString,
                response_deserializer=database__service__pb2.UserCallsignChangesResponse.FromString,
                _registered_method=True)
        self.InsertUserDiscordId = channel.unary_unary(
                '/DatabaseService/InsertUserDiscordId',
                request_serializer=database__service__pb2.InsertUserDiscordIdRequest.SerializeToString,
                response_deserializer=database__service__pb2.InsertUserDiscordIdResponse.FromString,
                _registered_method=True)
        self.UpdateUserForceCode = channel.unary_unary(
                '/DatabaseService/UpdateUserForceCode',
                request_serializer=database__service__pb2.UpdateUserForceCodeRequest.SerializeToString,
                response_deserializer=database__service__pb2.UpdateUserForceCodeResponse.FromString,
                _registered_method=True)
        self.InsertNewGuild = channel.unary_unary(
                '/DatabaseService/InsertNewGuild',
                request_serializer=database__service__pb2.InsertNewGuildRequest.SerializeToString,
                response_deserializer=database__service__pb2.InsertNewGuildResponse.FromString,
                _registered_method=True)
        self.GetConfigurationKeys = channel.unary_unary(
                '/DatabaseService/GetConfigurationKeys',
                request_serializer=database__service__pb2.GetConfigurationKeysRequest.SerializeToString,
                response_deserializer=database__service__pb2.GetConfigurationKeysResponse.FromString,
                _registered_method=True)
        self.UpdateConfigurationKeys = channel.unary_unary(
                '/DatabaseService/UpdateConfigurationKeys',
                request_serializer=database__service__pb2.UpdateConfigurationKeysRequest.SerializeToString,
                response_deserializer=database__service__pb2.UpdateConfigurationKeysResponse.FromString,
                _registered_method=True)
        self.GetAllOfKey = channel.unary_unary(
                '/DatabaseService/GetAllOfKey',
                request_serializer=database__service__pb2.GetAllOfKeyRequest.SerializeToString,
                response_deserializer=database__service__pb2.GetAllOfKeyResponse.FromString,
                _registered_method=True)
        self.GetForceUsers = channel.unary_unary(
                '/DatabaseService/GetForceUsers',
                request_serializer=database__service__pb2.GetForceUsersRequest.SerializeToString,
                response_deserializer=database__service__pb2.GetForceUsersResponse.FromString,
                _registered_method=True)
        self.InsertPatrolLog = channel.unary_unary(
                '/DatabaseService/InsertPatrolLog',
                request_serializer=database__service__pb2.InsertPatrolLogRequest.SerializeToString,
                response_deserializer=database__service__pb2.InsertPatrolLogResponse.FromString,
                _registered_method=True)


class DatabaseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserCallsignChanges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertUserDiscordId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserForceCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertNewGuild(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfigurationKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConfigurationKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllOfKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetForceUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertPatrolLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserCallsignChanges': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserCallsignChanges,
                    request_deserializer=database__service__pb2.UserCallsignChangesRequest.FromString,
                    response_serializer=database__service__pb2.UserCallsignChangesResponse.SerializeToString,
            ),
            'InsertUserDiscordId': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertUserDiscordId,
                    request_deserializer=database__service__pb2.InsertUserDiscordIdRequest.FromString,
                    response_serializer=database__service__pb2.InsertUserDiscordIdResponse.SerializeToString,
            ),
            'UpdateUserForceCode': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserForceCode,
                    request_deserializer=database__service__pb2.UpdateUserForceCodeRequest.FromString,
                    response_serializer=database__service__pb2.UpdateUserForceCodeResponse.SerializeToString,
            ),
            'InsertNewGuild': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertNewGuild,
                    request_deserializer=database__service__pb2.InsertNewGuildRequest.FromString,
                    response_serializer=database__service__pb2.InsertNewGuildResponse.SerializeToString,
            ),
            'GetConfigurationKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfigurationKeys,
                    request_deserializer=database__service__pb2.GetConfigurationKeysRequest.FromString,
                    response_serializer=database__service__pb2.GetConfigurationKeysResponse.SerializeToString,
            ),
            'UpdateConfigurationKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfigurationKeys,
                    request_deserializer=database__service__pb2.UpdateConfigurationKeysRequest.FromString,
                    response_serializer=database__service__pb2.UpdateConfigurationKeysResponse.SerializeToString,
            ),
            'GetAllOfKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllOfKey,
                    request_deserializer=database__service__pb2.GetAllOfKeyRequest.FromString,
                    response_serializer=database__service__pb2.GetAllOfKeyResponse.SerializeToString,
            ),
            'GetForceUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetForceUsers,
                    request_deserializer=database__service__pb2.GetForceUsersRequest.FromString,
                    response_serializer=database__service__pb2.GetForceUsersResponse.SerializeToString,
            ),
            'InsertPatrolLog': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertPatrolLog,
                    request_deserializer=database__service__pb2.InsertPatrolLogRequest.FromString,
                    response_serializer=database__service__pb2.InsertPatrolLogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DatabaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DatabaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DatabaseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserCallsignChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DatabaseService/GetUserCallsignChanges',
            database__service__pb2.UserCallsignChangesRequest.SerializeToString,
            database__service__pb2.UserCallsignChangesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertUserDiscordId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DatabaseService/InsertUserDiscordId',
            database__service__pb2.InsertUserDiscordIdRequest.SerializeToString,
            database__service__pb2.InsertUserDiscordIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserForceCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DatabaseService/UpdateUserForceCode',
            database__service__pb2.UpdateUserForceCodeRequest.SerializeToString,
            database__service__pb2.UpdateUserForceCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertNewGuild(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DatabaseService/InsertNewGuild',
            database__service__pb2.InsertNewGuildRequest.SerializeToString,
            database__service__pb2.InsertNewGuildResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfigurationKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DatabaseService/GetConfigurationKeys',
            database__service__pb2.GetConfigurationKeysRequest.SerializeToString,
            database__service__pb2.GetConfigurationKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConfigurationKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DatabaseService/UpdateConfigurationKeys',
            database__service__pb2.UpdateConfigurationKeysRequest.SerializeToString,
            database__service__pb2.UpdateConfigurationKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllOfKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DatabaseService/GetAllOfKey',
            database__service__pb2.GetAllOfKeyRequest.SerializeToString,
            database__service__pb2.GetAllOfKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetForceUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DatabaseService/GetForceUsers',
            database__service__pb2.GetForceUsersRequest.SerializeToString,
            database__service__pb2.GetForceUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertPatrolLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DatabaseService/InsertPatrolLog',
            database__service__pb2.InsertPatrolLogRequest.SerializeToString,
            database__service__pb2.InsertPatrolLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
