# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: database_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'database_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64\x61tabase_service.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"t\n\x17UserCallsignChangeEvent\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0cold_callsign\x18\x02 \x01(\t\x12\x14\n\x0cnew_callsign\x18\x03 \x01(\t\"G\n\x1bUserCallsignChangesResponse\x12(\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x18.UserCallsignChangeEvent\"6\n\x1aUserCallsignChangesRequest\x12\x18\n\x10geofs_account_id\x18\x01 \x01(\x03\"J\n\x1aInsertUserDiscordIdRequest\x12\x18\n\x10geofs_account_id\x18\x01 \x01(\x03\x12\x12\n\ndiscord_id\x18\x02 \x01(\x03\".\n\x1bInsertUserDiscordIdResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"^\n\x1aUpdateUserForceCodeRequest\x12\x18\n\x10geofs_account_id\x18\x01 \x01(\x03\x12\x12\n\ndiscord_id\x18\x02 \x01(\x03\x12\x12\n\nforce_code\x18\x03 \x01(\t\".\n\x1bUpdateUserForceCodeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x8a\x02\n\x0f\x44\x61tabaseService\x12S\n\x16GetUserCallsignChanges\x12\x1b.UserCallsignChangesRequest\x1a\x1c.UserCallsignChangesResponse\x12P\n\x13InsertUserDiscordId\x12\x1b.InsertUserDiscordIdRequest\x1a\x1c.InsertUserDiscordIdResponse\x12P\n\x13UpdateUserForceCode\x12\x1b.UpdateUserForceCodeRequest\x1a\x1c.UpdateUserForceCodeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERCALLSIGNCHANGEEVENT']._serialized_start=59
  _globals['_USERCALLSIGNCHANGEEVENT']._serialized_end=175
  _globals['_USERCALLSIGNCHANGESRESPONSE']._serialized_start=177
  _globals['_USERCALLSIGNCHANGESRESPONSE']._serialized_end=248
  _globals['_USERCALLSIGNCHANGESREQUEST']._serialized_start=250
  _globals['_USERCALLSIGNCHANGESREQUEST']._serialized_end=304
  _globals['_INSERTUSERDISCORDIDREQUEST']._serialized_start=306
  _globals['_INSERTUSERDISCORDIDREQUEST']._serialized_end=380
  _globals['_INSERTUSERDISCORDIDRESPONSE']._serialized_start=382
  _globals['_INSERTUSERDISCORDIDRESPONSE']._serialized_end=428
  _globals['_UPDATEUSERFORCECODEREQUEST']._serialized_start=430
  _globals['_UPDATEUSERFORCECODEREQUEST']._serialized_end=524
  _globals['_UPDATEUSERFORCECODERESPONSE']._serialized_start=526
  _globals['_UPDATEUSERFORCECODERESPONSE']._serialized_end=572
  _globals['_DATABASESERVICE']._serialized_start=575
  _globals['_DATABASESERVICE']._serialized_end=841
# @@protoc_insertion_point(module_scope)
