# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import get_user_callsign_changes_pb2 as get__user__callsign__changes__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in get_user_callsign_changes_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserCallsignChangesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserCallsignChanges = channel.unary_unary(
                '/UserCallsignChangesService/GetUserCallsignChanges',
                request_serializer=get__user__callsign__changes__pb2.UserCallsignChangesRequest.SerializeToString,
                response_deserializer=get__user__callsign__changes__pb2.UserCallsignChangesResponse.FromString,
                _registered_method=True)


class UserCallsignChangesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserCallsignChanges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserCallsignChangesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserCallsignChanges': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserCallsignChanges,
                    request_deserializer=get__user__callsign__changes__pb2.UserCallsignChangesRequest.FromString,
                    response_serializer=get__user__callsign__changes__pb2.UserCallsignChangesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserCallsignChangesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('UserCallsignChangesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserCallsignChangesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserCallsignChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserCallsignChangesService/GetUserCallsignChanges',
            get__user__callsign__changes__pb2.UserCallsignChangesRequest.SerializeToString,
            get__user__callsign__changes__pb2.UserCallsignChangesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
