# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: get_user_callsign_changes.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'get_user_callsign_changes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fget_user_callsign_changes.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"t\n\x17UserCallsignChangeEvent\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0cold_callsign\x18\x02 \x01(\t\x12\x14\n\x0cnew_callsign\x18\x03 \x01(\t\"G\n\x1bUserCallsignChangesResponse\x12(\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x18.UserCallsignChangeEvent\"6\n\x1aUserCallsignChangesRequest\x12\x18\n\x10geofs_account_id\x18\x01 \x01(\x05\x32q\n\x1aUserCallsignChangesService\x12S\n\x16GetUserCallsignChanges\x12\x1b.UserCallsignChangesRequest\x1a\x1c.UserCallsignChangesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_user_callsign_changes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERCALLSIGNCHANGEEVENT']._serialized_start=68
  _globals['_USERCALLSIGNCHANGEEVENT']._serialized_end=184
  _globals['_USERCALLSIGNCHANGESRESPONSE']._serialized_start=186
  _globals['_USERCALLSIGNCHANGESRESPONSE']._serialized_end=257
  _globals['_USERCALLSIGNCHANGESREQUEST']._serialized_start=259
  _globals['_USERCALLSIGNCHANGESREQUEST']._serialized_end=313
  _globals['_USERCALLSIGNCHANGESSERVICE']._serialized_start=315
  _globals['_USERCALLSIGNCHANGESSERVICE']._serialized_end=428
# @@protoc_insertion_point(module_scope)
