syntax = "proto3";
import "google/protobuf/timestamp.proto";
import "google/protobuf/any.proto";



service DatabaseService {
    rpc GetUserCallsignChanges (UserCallsignChangesRequest) returns (UserCallsignChangesResponse);
    rpc InsertUserDiscordId (InsertUserDiscordIdRequest) returns (InsertUserDiscordIdResponse);
    rpc UpdateUserForceCode (UpdateUserForceCodeRequest) returns (UpdateUserForceCodeResponse);
    rpc InsertNewGuild (InsertNewGuildRequest) returns (InsertNewGuildResponse);
    rpc GetConfigurationKeys (GetConfigurationKeysRequest) returns (GetConfigurationKeysResponse);
    rpc UpdateConfigurationKeys (UpdateConfigurationKeysRequest) returns (UpdateConfigurationKeysResponse);
    rpc GetAllOfKey (GetAllOfKeyRequest) returns (GetAllOfKeyResponse);
    rpc GetForceUsers (GetForceUsersRequest) returns (GetForceUsersResponse);
    rpc InsertPatrolLog (InsertPatrolLogRequest) returns (InsertPatrolLogResponse);
    rpc DeletePatrolLog (DeletePatrolLogRequest) returns (DeletePatrolLogResponse);
    rpc GetAllOnlinePilots (GetAllOnlinePilotsRequest) returns (GetAllOnlinePilotsResponse);
    rpc InsertKillLog (InsertKillLogRequest) returns (InsertKillLogResponse);
    rpc DeleteKillLog (DeleteKillLogRequest) returns (DeleteKillLogResponse);
    rpc GetCallsignFilters (GetCallsignFiltersRequest) returns (GetCallsignFiltersResponse);
    rpc InsertCallsignFilter (InsertCallsignFilterRequest) returns (InsertCallsignFilterResponse);
    rpc DeleteCallsignFilter (DeleteCallsignFilterRequest) returns (DeleteCallsignFilterResponse);
    rpc JoinPatrols (JoinPatrolsRequest) returns (JoinPatrolsResponse);
    rpc GetPatrolLogs (GetPatrolLogsRequest) returns (GetPatrolLogsResponse);
    rpc GetPatrolHours (GetPatrolHoursRequest) returns (GetPatrolHoursResponse);
}

message UserCallsignChangeEvent {
    google.protobuf.Timestamp timestamp = 1;
    string old_callsign = 2;
    string new_callsign = 3;
}

message UserCallsignChangesResponse {
    repeated UserCallsignChangeEvent events = 1;
}

message UserCallsignChangesRequest {
    int64 geofs_account_id = 1;
}

message InsertUserDiscordIdRequest {
    int64 geofs_account_id = 1;
    int64 discord_id = 2;
}

message InsertUserDiscordIdResponse {
    bool success = 1;
}

message UpdateUserForceCodeRequest {
    int64 geofs_account_id = 1;
    int64 discord_id = 2;
    int64 guild_id = 3;
}

message UpdateUserForceCodeResponse {
    bool success = 1;
}

message InsertNewGuildRequest {
    int64 guild_id = 1;
}

message InsertNewGuildResponse {
    bool success = 1;
}

message GetConfigurationKeysRequest {
    int64 guild_id = 1;
}

message Value {
    oneof value {
        string string_value = 1;
        int64 int_value = 2;
        bool bool_value = 3;
        google.protobuf.Timestamp timestamp_value = 4;
    }
}

message GetConfigurationKeysResponse {
    map<string, google.protobuf.Any> keys = 1;
}

message UpdateConfigurationKeysRequest {
    int64 guild_id = 1;
    string key = 2;
    string value = 3;
}

message UpdateConfigurationKeysResponse {
    bool success = 1;
}

message GetAllOfKeyRequest {
    string key = 1;
}

message GetAllOfKeyResponse {
    map<int64, google.protobuf.Any> keys = 1;
}

message GetForceUsersRequest {
    int64 guild_id = 1;
}

message UserDict {
    int64 discord_id = 1;
    int64 geofs_account_id = 2;
}

message GetForceUsersResponse {
    repeated UserDict users = 1;
}

message InsertPatrolLogRequest {
    int64 discord_id = 1;
    int64 guild_id = 2;
    google.protobuf.Timestamp start_datetime = 3;
    google.protobuf.Timestamp end_datetime = 4;
}

message InsertPatrolLogResponse {
    map<string, google.protobuf.Any> patrol_report = 1;
}

message DeletePatrolLogRequest {
    int64 event_id = 1;
    int64 guild_id = 2;
}

message DeletePatrolLogResponse {
    int64 response_code = 1;
}

message PatrolReport {
    int64 event_id = 1;
    int64 discord_id = 2;
    google.protobuf.Timestamp start_datetime = 3;
    google.protobuf.Timestamp end_datetime = 4;
}

message GetAllOnlinePilotsRequest {
    int64 guild_id = 1;
}

message GetAllOnlinePilotsResponse {
    repeated int64 discord_ids = 1;
}

message InsertKillLogRequest {
    int64 discord_id = 1;
    int64 guild_id = 2;
}

message InsertKillLogResponse {
    int64 event_id = 1;
    int64 kill_count = 2;
    google.protobuf.Timestamp timestamp = 3;
}

message DeleteKillLogRequest {
    int64 event_id = 1;
    int64 guild_id = 2;
}

message DeleteKillLogResponse {
    int64 response_code = 1;
}

message GetCallsignFiltersRequest {
    int64 guild_id = 1;
}

message GetCallsignFiltersResponse {
    repeated string filters = 1;
}

message InsertCallsignFilterRequest {
    int64 guild_id = 1;
    string callsign_filter = 2;
}

message InsertCallsignFilterResponse {
    bool success = 1;
}

message DeleteCallsignFilterRequest {
    int64 guild_id = 1;
    string callsign_filter = 2;
}

message DeleteCallsignFilterResponse {
    bool success = 1;
}

message JoinPatrolsRequest {
    int64 first_event_id = 1;
    int64 second_event_id = 2;
    int64 guild_id = 3;
}

message JoinPatrolsResponse {
    int64 response_code = 1;
}

message GetPatrolLogsRequest {
    int64 guild_id = 1;
    google.protobuf.Timestamp minimum_date = 2;
    int64 discord_id = 3;
}

message GetPatrolLogsResponse {
    repeated PatrolReport patrol_reports = 1;
}

message GetPatrolHoursRequest {
    int64 guild_id = 1;
    google.protobuf.Timestamp minimum_date = 2;
    int64 discord_id = 3;
}

message GetPatrolHoursResponse {
    double patrol_hours = 1;
}