syntax = "proto3";
import "google/protobuf/timestamp.proto";
import "google/protobuf/any.proto";



service DatabaseService {
    rpc GetUserCallsignChanges (UserCallsignChangesRequest) returns (UserCallsignChangesResponse);
    rpc InsertUserDiscordId (InsertUserDiscordIdRequest) returns (InsertUserDiscordIdResponse);
    rpc UpdateUserForceCode (UpdateUserForceCodeRequest) returns (UpdateUserForceCodeResponse);
    rpc InsertNewGuild (InsertNewGuildRequest) returns (InsertNewGuildResponse);
    rpc GetConfigurationKeys (GetConfigurationKeysRequest) returns (GetConfigurationKeysResponse);
}

message UserCallsignChangeEvent {
    google.protobuf.Timestamp timestamp = 1;
    string old_callsign = 2;
    string new_callsign = 3;
}

message UserCallsignChangesResponse {
    repeated UserCallsignChangeEvent events = 1;
}

message UserCallsignChangesRequest {
    int64 geofs_account_id = 1;
}

message InsertUserDiscordIdRequest {
    int64 geofs_account_id = 1;
    int64 discord_id = 2;
}

message InsertUserDiscordIdResponse {
    bool success = 1;
}

message UpdateUserForceCodeRequest {
    int64 geofs_account_id = 1;
    int64 discord_id = 2;
    string force_code = 3;
}

message UpdateUserForceCodeResponse {
    bool success = 1;
}

message InsertNewGuildRequest {
    int64 guild_id = 1;
}

message InsertNewGuildResponse {
    bool success = 1;
}

message GetConfigurationKeysRequest {
    int64 guild_id = 1;
}

message Value {
    oneof value {
        string string_value = 1;
        int64 int_value = 2;
        bool bool_value = 3;
        google.protobuf.Timestamp timestamp_value = 4;
    }
}

message GetConfigurationKeysResponse {
    map<string, google.protobuf.Any> keys = 1;
}