syntax = "proto3";
import "google/protobuf/timestamp.proto";


service DatabaseService {
    rpc GetUserCallsignChanges (UserCallsignChangesRequest) returns (UserCallsignChangesResponse);
    rpc InsertUserDiscordId (InsertUserDiscordIdRequest) returns (InsertUserDiscordIdResponse);
    rpc UpdateUserForceCode (UpdateUserForceCodeRequest) returns (UpdateUserForceCodeResponse);
}

message UserCallsignChangeEvent {
    google.protobuf.Timestamp timestamp = 1;
    string old_callsign = 2;
    string new_callsign = 3;
}

message UserCallsignChangesResponse {
    repeated UserCallsignChangeEvent events = 1;
}

message UserCallsignChangesRequest {
    int64 geofs_account_id = 1;
}

message InsertUserDiscordIdRequest {
    int64 geofs_account_id = 1;
    int64 discord_id = 2;
}

message InsertUserDiscordIdResponse {
    bool success = 1;
}

message UpdateUserForceCodeRequest {
    int64 geofs_account_id = 1;
    int64 discord_id = 2;
    string force_code = 3;
}

message UpdateUserForceCodeResponse {
    bool success = 1;
}